# Settings
baseurl: /class-boilerplate
permalink: pretty

# About
title: Class boilerplate
tagline: A Jekyll template for LMS
authors:
  - name: Luca De Feo
    url: 'http://defeo.lu'
created: 2014
license:
  name: MIT license
  shortname: MIT license
  url: /LICENSE
forkme: yes

create:
  pages: yes
  
# Collections
collections:
  addons:
    output: true

kramdown:
  parse_block_html: true

sass:
  sass_dir: assets/css
  style: compressed
